name: Subscriber Database Migration and Testing
run-name: ${{ github.actor }} is deploying subscriber database migrations 🚀
on: [push, pull_request]

jobs:
  setup_and_migrate_database:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: subscriber_db
          MYSQL_USER: subscriber_user
          MYSQL_PASSWORD: SubscriberPass123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" -u"subscriber_user" -p"SubscriberPass123" --silent; do
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Pull Flyway Docker image
        run: docker pull flyway/flyway:9-alpine

      - name: Run Flyway Migrations
        run: |
          echo "Running all Flyway migrations..."
          docker run --rm \
            -v "${{ github.workspace }}/migrations:/flyway/sql" \
            --network host \
            flyway/flyway:9-alpine \
            -url=jdbc:mysql://127.0.0.1:3306/subscriber_db \
            -user=subscriber_user \
            -password=SubscriberPass123 \
            migrate

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python pytest

      - name: Run Database Tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: subscriber_user
          DB_PASSWORD: SubscriberPass123
          DB_NAME: subscriber_db
        run: |
          echo "Running CRUD operation tests..."
          python -m pytest tests/test_subscriber_crud.py -v

      - name: Verify Database Schema
        run: |
          echo "Verifying database schema..."
          mysql -h 127.0.0.1 -P 3306 -u subscriber_user -pSubscriberPass123 subscriber_db -e "
            SHOW TABLES;
            SELECT COUNT(*) as subscriber_count FROM subscribers;
            SELECT COUNT(*) as preferences_count FROM subscription_preferences;
            SELECT COUNT(*) as history_count FROM subscription_history;
            SELECT COUNT(*) as flyway_count FROM flyway_schema_history;
          "

      - name: Deployment Complete
        run: |
          echo "🎉 Subscriber database deployment completed successfully!"
          echo "📊 Database: subscriber_db"
          echo "👤 User: subscriber_user"
          echo "🔗 Tables: subscribers, subscription_preferences, subscription_history"
          echo "✅ All migrations applied and tests passed"